name: Deploy to VPS with PM2

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20
  DEPLOY_ARCHIVE: deploy.tar.gz

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: tourism
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --no-cache
      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_WHATSAPP=${{ secrets.NEXT_PUBLIC_WHATSAPP }}" >> $GITHUB_ENV
      - name: Build project
        run: npm run build

      - name: Debug VPS_PATH
        run: echo "VPS_PATH=${{ secrets.VPS_PATH }}"

      - name: Pack build files
        run: |
          tar czf ${{ env.DEPLOY_ARCHIVE }} \
            .next package.json package-lock.json next.config.ts public data

      - name: Upload archive to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          source: ${{ env.DEPLOY_ARCHIVE }}
          target: ${{ secrets.VPS_PATH }}

      - name: Extract archive and restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            rm -rf .next package.json package-lock.json next.config.ts node_modules public data || true
            tar xzf ${{ env.DEPLOY_ARCHIVE }}
            rm ${{ env.DEPLOY_ARCHIVE }}
            npm install
            pm2 restart ${{ secrets.APP_NAME }}
