name: Deploy to VPS with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: tourism
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          #cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Build project
        run: npm run build

      - name: Debug VPS_PATH
        run: echo VPS_PATH=${{ secrets.VPS_PATH }}

      - name: Clean VPS directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}   # new secret
          script: |
            rm -rf ${{ secrets.VPS_PATH }}/*
      - name: List build files
        run: |
          ls -lR .next
          ls -l package.json package-lock.json next.config.ts
      - name: Upload files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          source: |
            .next
            package.json
            package-lock.json
            next.config.ts
          target: ${{ secrets.VPS_PATH }}
      - name: Restart PM2 process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}   # new secret
          script: |
            cd ${{ secrets.VPS_PATH }}
            pm2 restart ${{ secrets.APP_NAME }}
